import pygame
items_data = [
    {"item_id": 1,"is_equiped":False, "name": "Quantum Core", "desc": "A powerful energy source from deep space.", "rarity": "Legendary", "damage": 0, "defense": 10, "energy_consumption": 50, "weight": 15, "value": 5000, "icon": "../assets/accessories/inv/inv000.png","upgrade_Cost":200, "upgrade": 0},
    {"item_id": 2,"is_equiped":True, "name": "Nano Shield", "desc": "Generates a temporary defense field.", "rarity": "Epic", "damage": 0, "defense": 40, "energy_consumption": 20, "weight": 8, "value": 2400, "icon": "../assets/accessories/inv/inv001.png","upgrade_Cost":200, "upgrade": 0},
    {"item_id": 3, "is_equiped":False,"name": "Cryo Module", "desc": "Freezes enemies on contact.", "rarity": "Rare", "damage": 25, "defense": 5, "energy_consumption": 15, "weight": 5, "value": 1500, "icon": "../assets/accessories/inv/inv002.png","upgrade_Cost":300, "upgrade": 0},
    {"item_id": 4,"is_equiped":False, "name": "Hyper Crystal", "desc": "Used for faster-than-light travel.", "rarity": "Legendary", "damage": 0, "defense": 0, "energy_consumption": 30, "weight": 12, "value": 4500, "icon": "../assets/accessories/inv/inv003.png","upgrade_Cost":200, "upgrade": 0},
    {"item_id": 5,"is_equiped":True, "name": "Photon Blaster", "desc": "Light-based weapon with immense power.", "rarity": "Epic", "damage": 70, "defense": 0, "energy_consumption": 40, "weight": 10, "value": 3200, "icon": "../assets/accessories/inv/inv004.png","upgrade_Cost":200, "upgrade": 3},
    {"item_id": 6,"is_equiped":False, "name": "Antimatter Canister", "desc": "Handle with extreme caution.", "rarity": "Legendary", "damage": 120, "defense": -20, "energy_consumption": 60, "weight": 20, "value": 6000, "icon": "../assets/accessories/inv/inv005.png","upgrade_Cost":200, "upgrade": 2},
    {"item_id": 7,"is_equiped":False, "name": "Magnetic Clamp", "desc": "Keeps large structures in place.", "rarity": "Common", "damage": 0, "defense": 10, "energy_consumption": 5, "weight": 6, "value": 800, "icon": "../assets/accessories/inv/inv006.png","upgrade_Cost":3454, "upgrade": 0},
    {"item_id": 8,"is_equiped":False, "name": "Neural Interface", "desc": "Connects directly to the pilot's brain.", "rarity": "Rare", "damage": 0, "defense": 5, "energy_consumption": 10, "weight": 3, "value": 1800, "icon": "../assets/accessories/inv/inv007.png","upgrade_Cost":200, "upgrade":5},
    {"item_id": 9, "is_equiped":False,"name": "Plasma Coil", "desc": "High-energy plasma storage unit.", "rarity": "Epic", "damage": 30, "defense": 10, "energy_consumption": 25, "weight": 7, "value": 2700, "icon": "../assets/accessories/inv/inv008.png","upgrade_Cost":6700, "upgrade": 0},
    {"item_id": 10,"is_equiped":False, "name": "Void Fragment", "desc": "A piece of the void, unstable but valuable.", "rarity": "Legendary", "damage": 50, "defense": 0, "energy_consumption": 50, "weight": 4, "value": 7000, "icon": "../assets/accessories/inv/inv009.png","upgrade_Cost":200, "upgrade": 0},
    {"item_id": 11,"is_equiped":False, "name": "Pulse Emitter", "desc": "Sends out detection pulses.", "rarity": "Common", "damage": 0, "defense": 0, "energy_consumption": 5, "weight": 2, "value": 500, "icon": "../assets/accessories/inv/inv010.png","upgrade_Cost":2460, "upgrade": 0},
    {"item_id": 12,"is_equiped":False, "name": "Graviton Engine", "desc": "Allows control over gravity fields.", "rarity": "Rare", "damage": 0, "defense": 20, "energy_consumption": 10, "weight": 18, "value": 2000, "icon": "../assets/accessories/inv/inv011.png","upgrade_Cost":200, "upgrade": 0},
    {"item_id": 13,"is_equiped":False, "name": "Singularity Core", "desc": "Generates micro black holes.", "    ": "Legendary", "damage": 150, "defense": -30, "energy_consumption": 80, "weight": 22, "value": 10000, "icon": "../assets/accessories/inv/inv012.png","upgrade_Cost":200, "upgrade": 0},
    {"item_id": 14,"is_equiped":True, "name": "Omega Circuit", "desc": "An ancient piece of unknown tech.", "rarity": "Epic", "damage": 20, "defense": 15, "energy_consumption": 12, "weight": 6, "value": 3000, "icon": "../assets/accessories/inv/inv013.png","upgrade_Cost":200, "upgrade": 0},
    {"item_id": 15,"is_equiped":False, "name": "Cryo Chip", "desc": "Controls extreme temperature environments.", "rarity": "Rare", "damage": 10, "defense": 5, "energy_consumption": 7, "weight": 4, "value": 1400, "icon": "../assets/accessories/inv/inv014.png","upgrade_Cost":200, "upgrade": 0},
    {"item_id": 16,"is_equiped":False, "name": "Asteroid Cookie", "desc": "Bizarre edible rock with minerals.", "rarity": "Common", "damage": 0, "defense": 0, "energy_consumption": 0, "weight": 1, "value": 50, "icon": "../assets/accessories/inv/inv015.png","upgrade_Cost":200, "upgrade": 0},
    {"item_id": 17,"is_equiped":False, "name": "Warp Gem", "desc": "Enables instant travel between systems.", "rarity": "Legendary", "damage": 0, "defense": 0, "energy_consumption": 0, "weight": 5, "value": 4800, "icon": "../assets/accessories/inv/inv016.png","upgrade_Cost":200, "upgrade": 0},
    {"item_id": 18,"is_equiped":True, "name": "Stellar Alloy", "desc": "The strongest known metal.", "rarity": "Rare", "damage": 0, "defense": 25, "energy_consumption": 0, "weight": 10, "value": 2100, "icon": "../assets/accessories/inv/inv017.png","upgrade_Cost":1030, "upgrade": 0},
    {"item_id": 19,"is_equiped":False, "name": "Orbital Scanner", "desc": "Maps planetary surfaces.", "rarity": "Common", "damage": 0, "defense": 0, "energy_consumption": 4, "weight": 3, "value": 600, "icon": "../assets/accessories/inv/inv018.png","upgrade_Cost":340, "upgrade": 3},
    {"item_id": 20, "is_equiped":False,"name": "Ion Thruster", "desc": "Provides precise maneuvering.", "rarity": "Rare", "damage": 0, "defense": 10, "energy_consumption": 15, "weight": 9, "value": 1600, "icon": "../assets/accessories/inv/inv019.png","upgrade_Cost":130, "upgrade": 0}
]
